import React from 'react';

const Contact = () => {
    return (
        <div>
            <h1>Contact Page</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus nemo corrupti unde voluptatem, ipsa tempora sed error dicta velit eveniet aperiam sunt ad, deserunt ullam. Quam sunt pariatur perferendis iure odit? Suscipit, praesentium expedita obcaecati unde illo, reiciendis nulla quos odio enim quibusdam sed similique, labore perspiciatis perferendis non beatae nisi cumque a ipsum harum sapiente aut voluptatum ex voluptate. Placeat repellat at incidunt odio repellendus provident ipsam perferendis enim similique, nisi sapiente ea aliquam doloribus illum modi optio commodi itaque fugit voluptatum, eos laborum magnam dignissimos eveniet. Qui quis quasi ullam, maxime temporibus dolores magni eaque omnis eligendi harum aliquid numquam unde possimus? Rerum sequi quas perferendis expedita distinctio. Voluptatibus neque ipsam delectus omnis numquam ipsa consectetur ullam! Vero illo voluptates unde molestias asperiores! Laudantium delectus asperiores minima architecto natus labore eum, vel ipsum voluptatum eos modi distinctio numquam cumque nulla consequuntur autem, minus dolorem quisquam. Saepe molestiae atque natus odio aliquid quos id ullam! Quis voluptates illum reprehenderit qui, modi eaque sequi, nihil consequuntur aliquam sapiente recusandae perferendis similique nulla fugiat, laborum dolorum. Vel dolorem, commodi tempore, voluptatum nulla amet eos rem cumque saepe nemo necessitatibus tenetur iusto, mollitia id placeat. Suscipit, aperiam accusantium! Explicabo tempore modi quae quos, possimus, consequatur voluptatibus ab quisquam odit atque qui at corporis. Saepe facere error unde at vitae est quibusdam fugit nemo officiis magnam atque accusantium alias minus consequatur voluptatibus, tempore asperiores placeat a sed veniam excepturi aliquam eius. Nemo quas inventore aspernatur pariatur repellat, molestias laudantium explicabo necessitatibus deserunt, non neque corporis autem ipsa ipsum at accusantium vero accusamus aperiam et adipisci eligendi dolore tempore magni ea. Dicta repudiandae, facilis amet blanditiis aspernatur obcaecati maxime tempora accusamus incidunt eum placeat aperiam sint dolore modi itaque reprehenderit perferendis at vel facere dolor error ipsam. Culpa, perferendis molestias. Animi totam, quam vel ex accusamus quia modi, harum aspernatur alias distinctio et repudiandae molestias quidem aliquam rerum magni! Veniam cumque odit nesciunt at deserunt illo deleniti harum. Dolorem facilis enim sed quidem, dolor repellat iure dignissimos, esse soluta commodi necessitatibus, veniam nam molestias velit doloribus exercitationem eveniet accusantium obcaecati itaque animi ratione aperiam!</p>
        </div>
    );
};

export default Contact;